//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace i_facility_IdleHandlerWithOptimization
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFgPartNoDet
    {
        public int fgPartId { get; set; }
        public Nullable<int> partId { get; set; }
        public string partCountMethod { get; set; }
        public Nullable<int> operationNo { get; set; }
        public string workOrderNo { get; set; }
        public string noOfPartsPerCycle { get; set; }
        public Nullable<int> isClosed { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> closedDate { get; set; }
        public Nullable<int> operatorId { get; set; }
        public Nullable<int> machineId { get; set; }
        public string correctedDate { get; set; }
        public string shift { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public string modifiedBy { get; set; }
    }
}
